checks:
  php:
    code_rating: true

filter:
  excluded_paths:
    - vendor/*

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    tests-and-coverage:
      environment:
        php: '7.4'
