language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

env:
  - DB_DSN=
  - DB_DSN=mysql://root:@localhost/lampager_test

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE lampager_test;'
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/coveralls
