language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql
  - postgresql

env:
  global:
    - COVERALLS_PARALLEL=true
  jobs:
    - DB_DSN=
    - DB_DSN=mysql://root:@localhost/lampager_test
    - DB_DSN=postgres://postgres:@localhost/lampager_test

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE lampager_test;'
  - psql -c 'create database lampager_test;' -U postgres
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/php-coveralls

notifications:
  webhooks: https://coveralls.io/webhook
